name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest

    env:
      PROJECT_PATH: src/MCInstall
      TEST_PROJECT: src/MCInstall.Test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Restore
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} -c release --no-restore

      - name: Test
        run: dotnet test ${{ env.TEST_PROJECT }} -c release
